{"name": "test_login_user[17647352440-yy123456-False-200002-用户名或密码错误]", "status": "broken", "statusDetails": {"message": "TypeError: can only concatenate str (not \"dict\") to str", "trace": "self = <testcases.api_test.test_01_login_erp.TestUserLogin object at 0x00000244C1F4B580>\nbase_url = 'https://erp-qa.qdjk.xyz', username = '17647352440'\npassword = 'yy123456', except_result = 'False', except_code = '200002'\nexcept_msg = '用户名或密码错误'\n\n    @allure.story(\"用例--登录用户\")\n    @pytest.mark.parametrize(\"username, password, except_result, except_code, except_msg\",\n                             login_data[\"test_login_user\"])\n    def test_login_user(self,base_url, username, password, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n>       result = login_erp_user(base_url,username, password)\n\ntest_01_login_erp.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nbaseurl = 'https://erp-qa.qdjk.xyz', username = '17647352440'\npassword = 'yy123456'\n\n    def login_erp_user(baseurl, username, password):\n        \"\"\"\n        登录用户\n        :param username: 用户名\n        :param password: 密码\n        :return: 自定义的关键字返回结果 result\n        \"\"\"\n        url = baseurl + \"/erp-auth/auth/loginpassword\"\n        print(\"url:\"+url)\n        result = ResultBase()\n        payload = {\n            \"account\": username,\n            \"password\": password\n        }\n        header = {\n            \"Content-Type\": \"application/json\"\n        }\n        res = baseapi.all_send_requests(method=\"post\", url=url, json=payload, headers=header)\n>       print(\"res:\" + res)\nE       TypeError: can only concatenate str (not \"dict\") to str\n\n..\\..\\operation\\user.py:23: TypeError"}, "attachments": [{"name": "log", "source": "bc21aa84-dcca-42b3-bac1-1930c8a99c59-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "af5a342c-c75c-4251-9df6-32ecb77f8c8a-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "9a3386e2-1121-4664-9812-53c9c64fa9eb-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'17647352440'"}, {"name": "password", "value": "'yy123456'"}, {"name": "except_result", "value": "'False'"}, {"name": "except_code", "value": "'200002'"}, {"name": "except_msg", "value": "'用户名或密码错误'"}], "start": 1694411802240, "stop": 1694411803067, "uuid": "2831da4b-08cd-4778-b31d-39242493417f", "historyId": "c34e0cd68573d7a4c0dd7563c1b60da5", "testCaseId": "80c254abc9876d28cea0e8148b92d53d", "fullName": "testcases.api_test.test_01_login_erp.TestUserLogin#test_login_user", "labels": [{"name": "story", "value": "用例--登录用户"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "用户登录模块"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_01_login_erp"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "WIN-FOCJ805QQO5"}, {"name": "thread", "value": "19224-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_01_login_erp"}]}