{"name": "test_login_user[17647352440-yy123456-False-200002-用户名或密码错误]", "status": "passed", "attachments": [{"name": "log", "source": "4bef445c-4272-4f83-bdc8-fbb7f87452ad-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "d9667d3c-d169-4618-a36a-25a41bb8f8d7-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "0e9ac53b-8e82-4e9a-b06c-8f17344aeb21-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'17647352440'"}, {"name": "password", "value": "'yy123456'"}, {"name": "except_result", "value": "False"}, {"name": "except_code", "value": "200002"}, {"name": "except_msg", "value": "'用户名或密码错误'"}], "start": 1694413694240, "stop": 1694413694903, "uuid": "da5d4573-171d-4f48-8bf4-b4cfbf6c8814", "historyId": "c34e0cd68573d7a4c0dd7563c1b60da5", "testCaseId": "80c254abc9876d28cea0e8148b92d53d", "fullName": "testcases.api_test.test_01_login_erp.TestUserLogin#test_login_user", "labels": [{"name": "story", "value": "用例--登录用户"}, {"name": "severity", "value": "normal"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "feature", "value": "用户登录模块"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_01_login_erp"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "WIN-FOCJ805QQO5"}, {"name": "thread", "value": "23052-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_01_login_erp"}]}