{"name": "test_login_user[17647352440-yy123456-False-200002-用户名或密码错误]", "status": "passed", "attachments": [{"name": "log", "source": "aa26baca-6736-4612-9baf-db327cb617b7-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "4798208f-34eb-49b3-b0cb-3d0b840ea401-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "72da548b-0364-48e1-9895-3a7313705157-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'17647352440'"}, {"name": "password", "value": "'yy123456'"}, {"name": "except_result", "value": "False"}, {"name": "except_code", "value": "200002"}, {"name": "except_msg", "value": "'用户名或密码错误'"}], "start": 1694413777392, "stop": 1694413778033, "uuid": "5dac3da8-e320-4d96-881e-658ea59f6025", "historyId": "c34e0cd68573d7a4c0dd7563c1b60da5", "testCaseId": "80c254abc9876d28cea0e8148b92d53d", "fullName": "testcases.api_test.test_01_login_erp.TestUserLogin#test_login_user", "labels": [{"name": "story", "value": "用例--登录用户"}, {"name": "feature", "value": "用户登录模块"}, {"name": "severity", "value": "normal"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_01_login_erp"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "WIN-FOCJ805QQO5"}, {"name": "thread", "value": "17008-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_01_login_erp"}]}