{"name": "test_login_user[17647352440-yy123456-False-200002-用户名或密码错误]", "status": "passed", "attachments": [{"name": "log", "source": "ee8085f2-f8a7-4464-baf2-edfbb9492496-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "f4be0e4a-c41b-42d6-8d10-f3b7b1d8257b-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "c27fb91a-1df3-46ad-9e10-25a45b21a86f-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'17647352440'"}, {"name": "password", "value": "'yy123456'"}, {"name": "except_result", "value": "False"}, {"name": "except_code", "value": "200002"}, {"name": "except_msg", "value": "'用户名或密码错误'"}], "start": 1694413899064, "stop": 1694413899729, "uuid": "8359016a-0a2e-4f1f-a505-b9d0e30aa00d", "historyId": "c34e0cd68573d7a4c0dd7563c1b60da5", "testCaseId": "80c254abc9876d28cea0e8148b92d53d", "fullName": "testcases.api_test.test_01_login_erp.TestUserLogin#test_login_user", "labels": [{"name": "severity", "value": "normal"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "feature", "value": "用户登录模块"}, {"name": "story", "value": "用例--登录用户"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_01_login_erp"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "WIN-FOCJ805QQO5"}, {"name": "thread", "value": "21572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_01_login_erp"}]}