{"name": "test_login_user[17647352440-yy123456-False-200002-用户名或密码错误]", "status": "passed", "attachments": [{"name": "log", "source": "19367454-72c2-44fd-a2bc-4633a601407f-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "a32d59f0-f1e9-4f02-bf42-c1446c2d5572-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "7e3a9fd8-8240-4af8-8969-67cb0eef0736-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'17647352440'"}, {"name": "password", "value": "'yy123456'"}, {"name": "except_result", "value": "False"}, {"name": "except_code", "value": "200002"}, {"name": "except_msg", "value": "'用户名或密码错误'"}], "start": 1694413373945, "stop": 1694413374548, "uuid": "168d470b-5026-4cc0-8757-f09c2fe6fc33", "historyId": "c34e0cd68573d7a4c0dd7563c1b60da5", "testCaseId": "80c254abc9876d28cea0e8148b92d53d", "fullName": "testcases.api_test.test_01_login_erp.TestUserLogin#test_login_user", "labels": [{"name": "story", "value": "用例--登录用户"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "feature", "value": "用户登录模块"}, {"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_01_login_erp"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "WIN-FOCJ805QQO5"}, {"name": "thread", "value": "23564-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_01_login_erp"}]}